Initial Draft
kedro-org/publish-kedro-viz pull request #1
Opened 2024-03-10 02:51 UTC by ravi-kumar-pilla

## Description

Resolves https://github.com/kedro-org/kedro-viz/issues/1780

## Development notes

This is an initial draft of kedro-viz-share action

- Add initial setup for the action
- Add `spaceflights-pandas-viz` Kedro starter to test the workflow
- Update README file

## QA notes

* Test workflow should pass and there should be a Kedro-Viz static site hosted

## Checklist

- [x] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [x] Updated the documentation to reflect the code changes
- [x] Added new entries to the `RELEASE.md` file
- [x] Added tests to cover my changes

2024-03-12 15:17 UTC, noklam commented on action.yml
> +    default: true
Are we sure this should be default to `true`? I recalled the last discussion is default to `false`, is there new discussion that I missed?

2024-03-12 15:19 UTC, noklam commented on action.yml
> +      with:
Same comment as before as I check https://github.com/kedro-org/kedro-viz/issues/1780 and didn't find any comments.

Should this action install python and library dependencies? In `test.yml` you have already setup python, why would viz need a different python version?

2024-03-12 15:28 UTC, ravi-kumar-pilla commented on action.yml
> +    default: true
Hi Nok, I remember when we discussed we were not sure on this and if we make default to `false`, most of the users will not provide this as an input. But I am happy to change it. I would like to know what @NeroOkwa and @rashidakanchwala think of this.

2024-03-12 15:42 UTC, ravi-kumar-pilla commented on action.yml
> +      with:
I added this as a foolproof, incase they miss the prerequisite but you are right we can remove this. But I think we should keep Kedro-Viz installation here, in case they do not have it in the requirements. What do you think ? @noklam

2024-03-12 15:54 UTC, rashidakanchwala commented on action.yml
> +    default: true
@astrojuanlu can comment here. I think for now we should set it at false, because it's still opt-in

2024-03-12 16:12 UTC, deepyaman requested changes

2024-03-12 16:12 UTC, deepyaman commented on action.yml
> +name: kedro-viz-share
`share-kedro-viz` (or `publish-kedro-viz`) sound nicer, and are more in line with how actions are named (with the verb first).

2024-03-12 16:12 UTC, deepyaman commented on action.yml
> +        force_orphan: true
Why not leave this up to the user, too? Happy to default to true.

2024-03-12 16:12 UTC, deepyaman commented on README.md
> +**NOTE:** While configuring your repository for GitHub Pages, you have two publishing source options. You can either choose a `branch` or `a custom GitHub Actions workflow`. If you choose a branch, t
```suggestion
**NOTE:** While configuring your repository for GitHub Pages, you have two publishing source options. You can either choose a branch or a custom GitHub Actions workflow. If you choose a branch, the build artifacts will be uploaded to the `publish_branch` you pass as an input to the action, which defaults to `gh-pages`. If you choose a custom GitHub Actions workflow, you need to mention that in the input `publishing_source` to the action and no artifacts/branch will be created. Please find more information on configuring a publishing source for github pages site in the [official docs](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site).
```

2024-03-12 16:12 UTC, deepyaman commented on action.yml
> +    - name: Upload Pages artifact
```suggestion
    - name: Upload GitHub Pages artifact
```
For consistency with other places

2024-03-12 16:12 UTC, deepyaman commented on action.yml
> +        python -m pip install "kedro-viz>=7.1.0"
Do you not need other requirements? Not 100% sure, just asking.

2024-03-12 16:12 UTC, deepyaman commented on action.yml
> +    #     cache: "pip"
```suggestion
```
Should this be here?

2024-03-12 16:13 UTC, deepyaman commented on action.yml
> +        python -m pip install "kedro-viz>=7.1.0"
Ah, I see https://github.com/kedro-org/kedro-viz-share/pull/1#discussion_r1521665364

2024-03-12 16:14 UTC, deepyaman commented on action.yml
> +      with:
Maybe you can just make sure Kedro-Viz is installed, instead of doing it for them? That way they can also choose their version of Kedro-Viz.

2024-03-12 16:37 UTC, rashidakanchwala commented on action.yml
> +name: kedro-viz-share
i do like share-kedro-viz more . 

since the above name was more or less voted, would love @NeroOkwa , @astrojuanlu , and @merelcht 's opinion here.

2024-03-12 16:39 UTC, ravi-kumar-pilla commented on action.yml
> +name: kedro-viz-share
I am happy to change, but I would ask the team as the name we have now got max votes.

2024-03-12 16:44 UTC, ravi-kumar-pilla commented on action.yml
> +    #     cache: "pip"
I will revert this. I was making changes based on Nok's comments

2024-03-12 16:54 UTC, ravi-kumar-pilla commented on action.yml
> +      with:
I think having it here will not affect if the version is already present as it will use it from cache and says requirement is already satisfied. It will be installed only if Kedro-Viz is not present. We also need a minimum version of Kedro-Viz 7.1.0 where `kedro viz build` command is introduced. I think having this here would be nice

2024-03-12 18:21 UTC, ravi-kumar-pilla commented on action.yml
> +    default: true
I have made this to a default - `false` for now

2024-03-13 13:18 UTC, rashidakanchwala commented on README.md
> +A GitHub action which deploys your Kedro-Viz static site on GitHub pages. This action helps in the automation of a deployment startegy mentioned in [platform agnostic sharing with Kedro-Viz](https://
```suggestion
Kedro-viz-share is a GitHub action that simplifies the process of deploying a Kedro-viz, which is a visual representation of your Kedro project, directly within the Git repository where your Kedro project is stored. By using this action, you can effortlessly showcase your Kedro-viz on GitPages. 

This action helps in the automation of a deployment strategy mentioned in [platform agnostic sharing with Kedro-Viz](https://docs.kedro.org/projects/kedro-viz/en/v8.0.1/platform_agnostic_sharing_with_kedro_viz.html#static-website-hosting-platforms-such-as-github-pages)
```

2024-03-13 13:20 UTC, rashidakanchwala commented on README.md
> +- **GitHub Pages Setup:** Configure your repository for [GitHub Pages](https://docs.github.com/en/pages/quickstart).
should we have one more pre-requisite 
- Create a Github repository with your Kedro project

2024-03-13 13:27 UTC, rashidakanchwala commented on README.md
> +- The GitHub workflow `Publish and share Kedro Viz` should start. You can find it in the Actions tab with your commit message.
```suggestion
- Once triggered, the GitHub workflow "Publish and share Kedro Viz" will automatically start and can be found in the Actions tab with your commit message.
```

2024-03-13 13:27 UTC, rashidakanchwala commented on README.md
> +- The GitHub workflow `Publish and share Kedro Viz` should start. You can find it in the Actions tab with your commit message.
[nit]

2024-03-13 13:31 UTC, rashidakanchwala commented on README.md
> +The list of third party actions used in this project, with due credits to their authors and license terms. More details can be found inside the folder of each action.
would it makes sense to list them here?

2024-03-13 13:32 UTC, rashidakanchwala commented on README.md
> +- Once the workflow is successfully completed, the artifacts of your Kedro-Viz static site will be uploaded to the `publish-branch` input specified to the action if your GitHub pages publishing sourc
[nit] 
```suggestion
- If the GitHub Pages publishing source is a branch, then the artifacts of your Kedro-Viz static site will be uploaded to the publish-branch input specified in the action upon successful completion of the workflow.
```

2024-03-13 15:16 UTC, ravi-kumar-pilla commented on action.yml
> +name: kedro-viz-share
Hi @deepyaman , It was an internal meeting with Kedro and Viz team. There was no previous poll... so no worries :) Thanks !

2024-03-13 15:40 UTC, noklam reviewed
I realised I never push the "submit review" buttons🥲

2024-03-13 15:49 UTC, ravi-kumar-pilla commented on README.md
> +```
Hi @noklam ,

I have mentioned that in `Configure the action` section. Also the inputs are not required and that is the reason I mentioned the default values. I tried something similar to the [checkout](https://github.com/actions/checkout/blob/main/README.md) action doc.

2024-03-13 15:51 UTC, rashidakanchwala approved these changes
LGTM! Super exciting. Thanks Ravi :)

2024-03-13 17:26 UTC, NeroOkwa approved these changes
LGTM!!

2024-03-13 19:29 UTC, noklam approved these changes

2024-03-14 14:16 UTC, merged